project:
  type: book

book:
  title: "CDD appendix"
  author: "Authors here--"
  date: "5/18/2023"
  search: true
  repo-url: https://github.com/lukembrowne/CDD-appendix
  repo-actions: [issue, source]
  downloads: [pdf]
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - calculating-neighborhood.qmd
    - linear_vs_nonlinear.qmd
    - calculating-marginal-effects.qmd
    - metaregression-comparisons.qmd
    - references.qmd
    
comments:
  hypothesis: false

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: show
    code-overflow: scroll
    code-tools: true
    code-copy: true

  pdf:
    documentclass: scrreprt

editor: visual

