project:
  type: book

book:
  title: "Appendix to Conspecific density dependence in plant communities: a theory-based toolkit for empirical studies"
  author: ""
  date: "10/31/2024"
  search: true
  repo-url: https://github.com/lukembrowne/CDD-appendix
  repo-actions: [issue, source]
  downloads: [pdf]
  page-navigation: true
  chapters:
    - index.qmd
    - calculating-neighborhood.qmd
    - calculating-marginal-effects.qmd
    - metaregression-comparisons.qmd
    - references.qmd
    
comments:
  hypothesis: false

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: show
    code-overflow: scroll
    code-tools: true
    code-copy: true
    embed-resources: true


  pdf:
    toc: true
    number-sections: true
    colorlinks: true

  docx:
    toc: true
    number-sections: true
    colorlinks: true

editor: visual

