# Preface

This document serves as an appendix to the manuscript ***Conspecific density dependence in plant communities: a theory-based toolkit for empirical studies***, with the goal of providing code and guidance on conducting analyses of density dependence following the best practices outlined in the main manuscript and based on the publication @hulsmann2024latitudinal.

It is important to note that for many steps in the analysis, there are valid alternative approaches that could be used to model the data, each with their own strengths. For example, while we have chosen to largely follow the modeling approach of Hülsmann et al. @hulsmann2024latitudinal that uses Generalized Additive Models (GAMs) to capture the flexible, nonlinear effects of density dependence, other researchers may prefer linear or nonlinear parametric models. The semi-parametric nature of GAMs offers the advantage of flexibility, helping to avoid biases—particularly when interactions between variables are not strictly linear, as discussed in @detto2019. However, this flexibility can come at the cost of statistical power. When the functional form of the relationships is well understood or can be reasonably inferred, parametric models may offer a more efficient alternative.

This document aims to provide a clear starting point for applying density dependence analyses, while recognizing that the choice of methods may need to be adapted to fit specific datasets and research questions.
